### ISSUE TITLE
Deperacation warning using / for division in Sass

### ISSUE THREAD

**Issue by pszalko** [nzbin/three-dots#18]
I have updated Sass compiler and now it prints deprecation warnings when compiling three-dots code: 

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($dot-width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
7 │ $dot-radius: $dot-width/2 !default;
  │              ^^^^^^^^^^^^
  ╵
    node_modules/three-dots/sass/_variables.scss 7:14                       @import
    node_modules/three-dots/sass/three-dots.scss 4:9                        @import
    stdin 2:9                                                               root stylesheet
```

**Comment by nzbin** [comment]
See https://github.com/twbs/bootstrap/issues/34051

**Comment by maurer2** [comment]
Hello, I believe this workaround should work:

https://github.com/ag-grid/ag-grid/issues/4495#issuecomment-879371559

**Comment by maurer2** [comment]
Hello, bootstrap provides a helper function for division: https://github.com/twbs/bootstrap/blob/5c1691ac3a7511e3ae0f1f619bfc0c848090efb5/scss/_functions.scss#L233-L273

Cheers

**Comment by nzbin** [comment]
I'm going to refactoring with dart-sass.

**Comment by nzbin** [comment]
@pszalko @maurer2 I have improved this issue, please try the new version.
