### ISSUE TITLE
17:100: ERROR: Unterminated string token

### ISSUE THREAD

**Issue by sergmain** [nzbin/three-dots#31]
An error while trying to use three-dots in Angular app

./src/app/app.module.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Transform failed with 1 error:
/metaheuristic-angular/src/app/components/app-view/app-view.component.scss:17:100: ERROR: Unterminated string token

repo - https://github.com/sergmain/metaheuristic-angular

**Comment by nzbin** [comment]
If you use the Angular < `12.0.0`, you should use the three-dots `2.x`

**Comment by nzbin** [comment]
Please check out this answer https://stackoverflow.com/a/72189400/6808169

**Comment by sergmain** [comment]
after rebuilding with turned off optimization, the error was that @use 'three-dots'; must be declared before any other declaration.

so, @use 'three-dots';  is working.

Then I've made a mistake and included  $dot-radius: $dot-width / 2, in with clause, like this
```
@use 'three-dots' with (
    $dot-width: 10px,
    $dot-height: 10px,
    $dot-radius: $dot-width / 2,
    $dot-color: #c22525

);
```
after removing $dot-radius: $dot-width / 2, everything started working perfectly.
