### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by Nevaan** [nzbin/three-dots#8]
Hi,

Is rebuilding whole project the only way to change dot colors? It tried to overwrite keyframes (in my case, the dot-pulse one) but it seems to change only middle dot color - the one before and after looks to stay violet. I cant see any other property I could change

Best regards

**Comment by grogy** [comment]
Are you using Sass for change it? Example for colors is in readme https://github.com/nzbin/three-dots#customization

**Comment by nh916** [comment]
it would be really nice to change colors with a css variable or something instead of having to recompile the whole project every time

**Comment by nat-sky** [comment]
I don't have _variables.scss in my project folder, how do I change the color???

**Comment by nzbin** [comment]
> I don't have _variables.scss in my project folder, how do I change the color???

In you use the dart sass, you can customize the dot in the following way.

```scss
@use 'three-dots/sass/three-dots' with (
  $dot-width: 20px,
  $dot-height: 20px,
  $dot-radius: 50%,
  $dot-color: blue
);
```
